name: WakaTime Stats Updater

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-wakatime:
    name: Updates README with WakaTime stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: NickRTR/WakaTime-Readme@main
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
